name: $(Build.BuildID)

trigger:
  - trunk

parameters:
  - name: agent
    type: string
    default: macOS-latest
    values:
      - macOS-latest
      - ubuntu-lastest
      - windows-latest
  - name: nodeVersion
    type: string
    default: "12.x"
variables:
  defaultName: "trunk"
  system.debug: true

stages:
  - stage: Build
    displayName: Build Stage
    pool:
      vmImage: ${{parameters.agent}}
    jobs:
      - job: Build_Docs
        displayName: Build Docs
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: "specific"
              project: "3e857acd-880f-4056-a46b-1de672ca55cc"
              definition: "62"
              buildVersionToDownload: "latestFromBranch"
              branchName: "refs/heads/trunk"
              artifactName: "Package"
              targetPath: "$(Pipeline.Workspace)"
          - task: NodeTool@0
            inputs:
              versionSpec: ${{parameters.nodeVersion}}
            displayName: "Install Node.js Version ${{parameters.nodeVersion}}"

          - script: yarn install
            displayName: yarn install

          - script: yarn build:VSTeamHelp
            displayName: generate VSTeam module docs
