parameters:
  - name: Deploy
    type: boolean
    default: true

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js Version 12.X'

  - script: |
      yarn install
      yarn run build
    displayName: 'docs build'

  - ${{ if eq(parameters.Deploy, true)}}:
    - script: |
        git config --global user.name "${GH_NAME}"
        git config --global user.email "${GH_EMAIL}"
        echo "machine github.com login ${GH_LOGIN} password ${GH_TOKEN}" > ~/.netrc
        git checkout master
        yarn install
        GIT_USER="${GH_LOGIN}" CURRENT_BRANCH=master yarn run deploy
      env:
        GH_NAME: $(GH_NAME)
        GH_LOGIN: $(GH_LOGIN)
        GH_EMAIL: $(GH_EMAIL)
        GH_TOKEN: $(GH_TOKEN)
      displayName: 'docs deploy'