parameters:
  - name: Deploy
    type: boolean
    default: true

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    displayName: Build
    jobs:
    - job: test_build
      displayName: Check Build
      steps:
        - template: ./tools/ci/azurepipelines/buildDocs.yml
  - stage: deploy
    displayName: Deploy GitHub Pages
    condition: and(succeeded(), and(eq(variables['System.PullRequest.IsFork'], false), eq(variables['Build.SourceBranch'],'refs/heads/master')))
    jobs:
    - deployment: Deploy
      displayName: Deploy Docs
      environment: GitHub Pages VSTeam Docs
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
              persistCredentials: true

            - template: ./tools/ci/azurepipelines/buildDocs.yml
            
            - script: |
                git config --global user.name "$(GH_NAME)"
                git config --global user.email "$(GH_EMAIL)"
                git checkout -b master
                echo "machine github.com login $(GH_LOGIN) password $(GH_TOKEN)" > ~/.netrc
                GIT_USER="$(GH_LOGIN)" yarn deploy
              displayName: 'docs deploy'
