parameters:
  - name: Deploy
    type: boolean
    default: true

trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    condition: and(succeeded(), eq(variables['System.PullRequest.IsFork'], true))
    displayName: Build
    jobs:
    - job: test_build
      displayName: Check Build
      steps:
        - template: ./tools/ci/azurepipelines/buildDocs.yml
  - stage: deploy
    displayName: Deploy GitHub Pages
    condition: and(succeeded(), and(eq(variables['System.PullRequest.IsFork'], false), eq(variables['Build.SourceBranch'],'refs/heads/master')))
    jobs:
    - deployment: Deploy
      displayName: Deploy Docs
      environment: GitHub Pages VSTeam Docs
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - template: ./tools/ci/azurepipelines/buildDocs.yml
            - script: |
                git config --global user.name "${GH_NAME}"
                git config --global user.email "${GH_EMAIL}"
                git checkout -b master
                echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
                yarn && GIT_USER="${GH_NAME}" yarn deploy
              env:
                GH_NAME: $(GH_NAME)
                GH_EMAIL: $(GH_EMAIL)
                GH_TOKEN: $(GH_TOKEN)
              displayName: 'docs deploy'
