name: $(Build.BuildID)

trigger:
  - trunk

parameters:
  - name: agent
    type: string
    default: macOS-latest
    values:
      - macOS-latest
      - ubuntu-lastest
      - windows-latest
  - name: nodeVersion
    type: string
    default: "12.x"
variables:
  defaultName: "trunk"
  system.debug: true

stages:
  - stage: Build
    displayName: Build Stage
    pool:
      vmImage: ${{parameters.agent}}
    jobs:
      - job: Build_Docs
        displayName: Build Docs
        steps:
          - task: NodeTool@0
            displayName: "install Node.js Version ${{parameters.nodeVersion}} on agent"
            inputs:
              versionSpec: ${{parameters.nodeVersion}}

          - task: YarnInstaller@3
            displayName: install yarn  Version 1.x on agent
            inputs:
              versionSpec: "1.x"

          - script: yarn install
            displayName: yarn install

          - task: DownloadPipelineArtifact@2
            displayName: download artifact from VSTeam
            inputs:
              buildType: "specific"
              project: "3e857acd-880f-4056-a46b-1de672ca55cc"
              definition: "62"
              buildVersionToDownload: "latestFromBranch"
              branchName: "refs/heads/trunk"
              artifactName: "Package"
              targetPath: "$(Pipeline.Workspace)/Package"

          - script: yarn build:VSTeamHelp -- XmlPath '$($Pipeline.Workspace)/Package/en-US/'
            displayName: generate VSTeam module docs

          - task: PublishPipelineArtifact@1
            displayName: publish markdown files
            inputs:
              targetPath: "$(Build.SourcesDirectory)/docs/modules/vsteam/commands"
              artifact: "docs"
              publishLocation: "pipeline"

  - stage: Deploy
    displayName: GitHub Pages
    dependsOn: Build
    pool:
      vmImage: ${{parameters.agent}}
    jobs:
      - deployment: Deploy
        displayName: GitHub Pages
        environment: "GitHub Pages"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: NodeTool@0
                  displayName: "install Node.js Version ${{parameters.nodeVersion}} on agent"
                  inputs:
                    versionSpec: ${{parameters.nodeVersion}}

                - task: YarnInstaller@3
                  displayName: install yarn  Version 1.x on agent
                  inputs:
                    versionSpec: "1.x"

                - checkout: self
                  persistCredentials: true

                - script: yarn install
                  displayName: yarn install

                - task: DownloadPipelineArtifact@2
                  displayName: download artifact from build stage
                  inputs:
                    buildType: "current"
                    artifactName: "docs"
                    targetPath: "$(Build.SourcesDirectory)/docs/modules/vsteam/commands"

                - script: |
                    git config --global user.name "${GH_NAME}"
                    git config --global user.email "${GH_EMAIL}"
                    git checkout -b trunk
                    echo "machine github.com login ${GH_LOGIN} password ${GH_TOKEN}" > ~/.netrc
                    GIT_USER="${GH_LOGIN}" yarn deploy
                  env:
                    GH_NAME: $(GH_NAME)
                    GH_EMAIL: $(GH_EMAIL)
                    GH_TOKEN: $(GH_TOKEN)
                    GH_LOGIN: $(GH_LOGIN)
                  displayName: push to GitHub Pages
