trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: github_vsteam
      type: github
      name: "MethodsAndPractices/vsteam"
      endpoint: VS-TeamPipelines

steps:
  - checkout: self
    persistCredentials: true
  - checkout: github_vsteam
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      git config --global user.name "${GH_NAME}"
      git config --global user.email "${GH_EMAIL}"
      git checkout -b master
      echo "machine github.com login ${GH_LOGIN} password ${GH_TOKEN}" > ~/.netrc
      cd website
      yarn install
      GIT_USER="${GH_LOGIN}" CURRENT_BRANCH=master yarn run deploy
    env:
      GH_NAME: $(GH_NAME)
      GH_LOGIN: $(GH_LOGIN)
      GH_EMAIL: $(GH_EMAIL)
      GH_TOKEN: $(GH_TOKEN)
    displayName: 'yarn install and build'
